# Generated by Django 2.2.4 on 2019-08-30 08:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='contact_no',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number is not in the correct format.', regex='^(\\+?91[\\-\\s]?)?[0]?(91)?[789]\\d{9}$')]),
        ),
    ]
