# Generated by Django 2.2.4 on 2019-09-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_contact_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='category',
            field=models.TextField(choices=[('FD', 'First Degree'), ('HD', 'Higer Degree'), ('PD', 'PhD')], default='FD'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='enrollment_year',
            field=models.PositiveIntegerField(default=2018),
            preserve_default=False,
        ),
    ]
