# Generated by Django 2.2.4 on 2019-08-17 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('C1', 'CATEGORY_1'), ('C2', 'CATEGORY_2'), ('C3', 'CATEGORY_3'), ('C4', 'CATEGORY_4')], max_length=2)),
                ('status', models.CharField(choices=[('RD', 'Registered'), ('DN', 'Done'), ('CD', 'Cancelled')], max_length=2)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField()),
                ('remark', models.TextField()),
                ('remark_to_user', models.TextField()),
                ('urgency', models.BooleanField(default=False)),
                ('urgency_reason', models.TextField()),
                ('contact_no', models.PositiveIntegerField()),
                ('room_no', models.TextField()),
                ('avail_start_time', models.TimeField()),
                ('avail_end_time', models.TimeField()),
                ('handler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handler', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complainer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
