# Generated by Django 2.2.4 on 2019-08-18 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('C1', 'CATEGORY_1'), ('C2', 'CATEGORY_2'), ('C3', 'CATEGORY_3'), ('C4', 'CATEGORY_4')], default='RD', max_length=2),
        ),
        migrations.CreateModel(
            name='UnblockRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('status', models.CharField(choices=[('RD', 'Registered'), ('DN', 'Done'), ('CD', 'Cancelled')], default='RD', max_length=2)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('remark_to_user', models.TextField()),
                ('handler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolver', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
