# Generated by Django 2.2.4 on 2019-08-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_auto_20190818_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('C1', 'CATEGORY_1'), ('C2', 'CATEGORY_2'), ('C3', 'CATEGORY_3'), ('C4', 'CATEGORY_4')], max_length=2),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('RD', 'Registered'), ('DN', 'Done'), ('CD', 'Cancelled')], default='RD', max_length=2),
        ),
    ]
