# Generated by Django 2.2.4 on 2019-08-20 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_auto_20190820_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unblockrequest',
            name='handler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='unblockrequest',
            name='remark_to_user',
            field=models.TextField(blank=True, null=True),
        ),
    ]
