# Generated by Django 2.2.4 on 2019-08-21 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_auto_20190820_2110'),
        ('complaints', '0006_auto_20190820_2014'),
    ]

    operations = [
    ]
