# Generated by Django 2.2.4 on 2019-08-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0009_auto_20190825_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[(None, 'Choose A Category'), ('LN', 'Lan'), ('WF', 'Wifi'), ('SF', 'Sophos Firewall')], max_length=2),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('RD', 'Registered'), ('TU', 'Issue Taken Up'), ('DN', 'Resolved'), ('CD', 'Cancelled')], default='RD', max_length=2),
        ),
    ]
