# Generated by Django 2.2.4 on 2019-09-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0010_auto_20190830_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unblockrequest',
            name='status',
            field=models.CharField(choices=[('RD', 'Registered'), ('VF', 'Verified'), ('DN', 'Done'), ('CD', 'Cancelled')], default='RD', max_length=2),
        ),
    ]
