# Generated by Django 2.2.4 on 2019-09-03 18:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0011_auto_20190901_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unblockrequest',
            name='url',
            field=models.TextField(validators=[django.core.validators.RegexValidator(message='This is not a valid URL.', regex='^(([^:/?#]+):)?(//([^/?#]*))?([^?#]*)(\\?([^#]*))?(#(.*))?')]),
        ),
    ]
