# Generated by Django 2.2.4 on 2019-09-09 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0014_complaint_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='avail_date',
            field=models.DateField(default=datetime.date(2019, 9, 9)),
            preserve_default=False,
        ),
    ]
