# Generated by Django 2.2.4 on 2019-09-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0015_complaint_avail_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='bhavan',
            field=models.CharField(choices=[(None, 'Bhavan'), ('K', 'Krishna'), ('R', 'Ram'), ('S', 'Shankar'), ('G', 'Gandhi'), ('B', 'Budh'), ('V', 'Vyas'), ('GT', 'Gautam'), ('VL', 'Valmiki'), ('ME', 'Meera'), ('ML', 'Malviya'), ('VK', 'Vishwakarma'), ('MR', 'MRS Tower'), ('H8', 'H8 Block')], default='VK', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint',
            name='room_no',
            field=models.PositiveIntegerField(),
        ),
    ]
