# Generated by Django 2.2.4 on 2019-09-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0016_auto_20190919_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='bhavan',
            field=models.CharField(choices=[(None, 'Bhavan'), ('K', 'Krishna'), ('R', 'Ram'), ('S', 'Shankar'), ('G', 'Gandhi'), ('B', 'Budh'), ('V', 'Vyas'), ('GT', 'Gautam'), ('VM', 'Valmiki'), ('M', 'Meera'), ('MM', 'Malviya'), ('VB', 'Vishwakarma Boys'), ('VG', 'Vishwakarma Girls'), ('MR', 'MRS Tower'), ('H8', 'H8 Block')], max_length=2),
        ),
    ]
